# todolist micro-service redis
bookstore-redis:
  container_name: todolist-redis
  image: xavmarc/todolist:latest
  restart: always
  environment:
    - URL_DB=${URL_DB}
  links:
    - redis
  ports:
    - "8020:8020"
  command: -port 8020 -db 0 -statd 5m

# bdd redis
redis:
  container_name: todolist-redis-db
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
